spreadsheet:
  id: <sheet id>
  sheet: <sheet name>
  data:
    row:
      data: 2
    minecraft:
      name: B
    types:
      - column: E
        scoreboard:
          name: youtube
          title: YouTube登録者数
      - column: L
        scoreboard:
          name: twitter
          title: Twitterフォロワー

credential:
  spreadsheet:
    token: <token>